Spree::SubscriptionFrequency.create(title: "daily", days_count: 1)
Spree::SubscriptionFrequency.create(title: "Every week", days_count: 7)
Spree::SubscriptionFrequency.create(title: "Every second week", days_count: 14)
Spree::SubscriptionFrequency.create(title: "Every third week", days_count: 21)
Spree::SubscriptionFrequency.create(title: "Every fouth week", days_count: 28)
